import fs from 'node:fs/promises'
import path from 'node:path'
import { ScanData } from './scanner'

function buildTree(paths: string[]): string {
  const tree: any = {}
  for (const p of paths) {
    let current = tree
    for (const part of p.split(path.sep)) {
      if (!current[part]) current[part] = {}
      current = current[part]
    }
  }

  function render(obj: any, indent: string = ''): string {
    let result = ''
    const keys = Object.keys(obj)
    keys.forEach((key, index) => {
      const isLast = index === keys.length - 1
      result += `${indent}${isLast ? '└── ' : '├── '}${key}\n`
      result += render(obj[key], indent + (isLast ? '    ' : '│   '))
    })
    return result
  }

  return render(tree)
}

export async function generateMap(rootDir: string, data: ScanData) {
  const mapDir = path.join(rootDir, '.ai', 'map')
  await fs.mkdir(mapDir, { recursive: true })

  // 1. STRUCTURE.md
  let structureMd = '# 📂 Repository Structure\n\n'
  structureMd += '## 🏛️ Categorized Folders\n\n| Path | Category | Responsibility |\n|------|----------|----------------|\n'
  const sorted = Object.entries(data.categories).sort(([a], [b]) => a.localeCompare(b)).slice(0, 50)
  for (const [path, cat] of sorted) {
    structureMd += `| \`${path}\` | **${cat}** | Core logic for ${cat.toLowerCase()} |\n`
  }
  structureMd += '\n## 🌲 Full Tree (Graphified)\n\n```text\n' + buildTree(data.structure) + '\n```\n'
  await fs.writeFile(path.join(mapDir, 'STRUCTURE.md'), structureMd)

  // 2. TECH_STACK.md
  let techMd = '# ⚙️ Tech Stack & Standards\n\n'
  data.techStack.forEach(t => techMd += `- ${t}\n`)
  techMd += '\n## 📜 Standards\n- Indentation: 2 spaces\n- Quotes: Single\n- TypeScript: Strict Mode\n'
  await fs.writeFile(path.join(mapDir, 'TECH_STACK.md'), techMd)

  // 3. ENTRY_POINTS.md
  let entryMd = '# 📍 Logic Entry Points\n\n'
  data.entryPoints.forEach(e => entryMd += `- \`${e}\`\n`)
  await fs.writeFile(path.join(mapDir, 'ENTRY_POINTS.md'), entryMd)

  // 4. AI_INSTRUCTIONS.md
  const instructions = `# 🗺️ CODEBASE MAP: AI NAVIGATION PROTOCOL

> **CRITICAL:** This repository is pre-mapped for token efficiency. DO NOT perform recursive directory listings or broad searches.

### 📍 Navigation Index
Read these files in order to understand the codebase without wasting context:
1. \`.ai/map/STRUCTURE.md\`: Architectural map & visual directory tree.
2. \`.ai/map/TECH_STACK.md\`: Standards, languages, and frameworks.
3. \`.ai/map/ENTRY_POINTS.md\`: Main entry points for application logic.

### 🛡️ Agent Rules
- **Rule 1:** Consult \`STRUCTURE.md\` before searching for files.
- **Rule 2:** Only read files directly required for the task.
- **Rule 3:** Trust the folder categorization to find relevant logic.

---
*Generated by Codebase Mapper*`
  await fs.writeFile(path.join(mapDir, 'AI_INSTRUCTIONS.md'), instructions)
}
