import fs from 'node:fs/promises';
import path from 'node:path';
import { CodeGraph, getTreeChildren } from './parser';

export async function generateAISummary(rootDir: string, graph: CodeGraph) {
    const mapperDir = path.join(rootDir, '.codebase-mapper');
    await fs.mkdir(mapperDir, { recursive: true });

    // 1. Generate Directory Tree
    function buildTreeString(parentPath: string, indent: string = ''): string {
        let result = '';
        const children = getTreeChildren(parentPath);
        
        // Sort: folders first, then files
        children.sort((a, b) => {
            if (a.type === b.type) return a.name.localeCompare(b.name);
            return a.type === 'folder' ? -1 : 1;
        });

        children.forEach((child, index) => {
            const isLast = index === children.length - 1;
            const prefix = isLast ? '└── ' : '├── ';
            result += `${indent}${prefix}${child.name}${child.type === 'folder' ? '/' : ''}\n`;
            if (child.type === 'folder') {
                result += buildTreeString(child.id, indent + (isLast ? '    ' : '│   '));
            }
        });
        return result;
    }

    const treeStr = buildTreeString('.');

    // 2. Identify Hotspots (most imported files)
    const importCounts = new Map<string, number>();
    graph.links.filter(l => l.type === 'import').forEach(link => {
        importCounts.set(link.target, (importCounts.get(link.target) || 0) + 1);
    });

    const hotspots = Array.from(importCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10);

    // 3. Generate README.md for AI Agents
    const readmeContent = `# 🗺️ CODEBASE MAP: AI NAVIGATION PROTOCOL

> **CRITICAL:** This repository is pre-indexed for token efficiency. 
> Use this map to navigate instead of performing broad searches.

## 🌲 Repository Structure
\`\`\`text
${treeStr}
\`\`\`

## 📍 Architectural Hotspots
The following files are heavily depended upon and likely contain core logic or shared types:
${hotspots.map(([path, count]) => `- \`${path}\` (${count} imports)`).join('\n')}

## 🛡️ Agent Guidance
- **Efficiency:** Consult this map before reading files.
- **Context:** The dependency graph is stored in \`graph.sqlite\` within this directory.
- **Visualization:** Run \`3d\` in this terminal to see the interactive version.

---
*Generated by Codebase Mapper*`;

    await fs.writeFile(path.join(mapperDir, 'README.md'), readmeContent);
    
    // 4. Update .gitignore
    const gitignorePath = path.join(rootDir, '.gitignore');
    try {
        const gitignore = await fs.readFile(gitignorePath, 'utf8');
        if (!gitignore.includes('.codebase-mapper/')) {
            await fs.appendFile(gitignorePath, '\n# Codebase Mapper\n.codebase-mapper/\n');
        }
    } catch (e) {
        // If no .gitignore, create one
        await fs.writeFile(gitignorePath, '# Codebase Mapper\n.codebase-mapper/\n');
    }
}
