import fs from 'node:fs/promises';
import path from 'node:path';
import { CodeGraph, getTreeChildren, GraphNode } from './parser';

export async function generateAISummary(rootDir: string, graph: CodeGraph) {
    const mapperDir = path.join(rootDir, '.codemap');
    await fs.mkdir(mapperDir, { recursive: true });

    // 1. Generate Plain Directory Tree (tree.txt)
    function buildTreeString(parentPath: string, indent: string = ''): string {
        let result = '';
        const children = getTreeChildren(parentPath);
        
        children.sort((a, b) => {
            if (a.type === b.type) return a.name.localeCompare(b.name);
            return a.type === 'folder' ? -1 : 1;
        });

        children.forEach((child, index) => {
            if (child.type === 'symbol') return; // Don't show symbols in tree.txt
            const isLast = index === children.length - 1;
            const prefix = isLast ? '└── ' : '├── ';
            result += `${indent}${prefix}${child.name}${child.type === 'folder' ? '/' : ''}\n`;
            if (child.type === 'folder') {
                result += buildTreeString(child.id, indent + (isLast ? '    ' : '│   '));
            }
        });
        return result;
    }

    const treeStr = buildTreeString('.');
    await fs.writeFile(path.join(mapperDir, 'tree.txt'), treeStr);

    // 2. Identify Entry Points
    const entryPointPatterns = ['index', 'main', 'app', 'server', 'entry'];
    const entryPoints = graph.nodes.filter(n => 
        n.type === 'file' && entryPointPatterns.some(p => n.name.toLowerCase().includes(p))
    );

    // 3. Generate summary.json (Machine Readable)
    const summaryJson = {
        project: path.basename(rootDir),
        stats: {
            files: graph.nodes.filter(n => n.type === 'file').length,
            folders: graph.nodes.filter(n => n.type === 'folder').length,
            symbols: graph.nodes.filter(n => n.type === 'symbol').length,
        },
        entryPoints: entryPoints.map(e => e.path),
        structure: treeStr.split('\n').filter(line => line.trim() !== ''),
        hotspots: getHotspots(graph),
        nodes: graph.nodes.map(n => ({
            id: n.id,
            name: n.name,
            type: n.type,
            path: n.path,
            meta: n.meta
        }))
    };
    await fs.writeFile(path.join(mapperDir, 'summary.json'), JSON.stringify(summaryJson, null, 2));

    // 4. Generate README.md (AI Context)
    const readmeContent = `# 🌌 Project Map: ${path.basename(rootDir)}

> **AI INSTRUCTIONS:** Use this map to navigate instead of broad searches. 
> The dependency graph is available in \`.codemap/summary.json\`.

## 🌲 Directory Structure
\`\`\`text
${treeStr}
\`\`\`

## 📍 Logic Entry Points
These are the primary entry points discovered in the project:
${entryPoints.map(e => `- \`${e.path}\``).join('\n')}

## 🚀 Architectural Hotspots
Most imported files (Likely core logic or shared types):
${getHotspots(graph).map(h => `- \`${h.path}\` (${h.count} imports)`).join('\n')}

## ⚙️ How to use
- **Read:** \`.codemap/summary.json\` for the full knowledge graph.
- **Visualize:** Run \`3d\` in the root to start the 3D server.

---
*Generated by Codebase Mapper*`;

    await fs.writeFile(path.join(mapperDir, 'README.md'), readmeContent);
    
    // 5. Update .gitignore
    const gitignorePath = path.join(rootDir, '.gitignore');
    try {
        const gitignore = await fs.readFile(gitignorePath, 'utf8');
        if (!gitignore.includes('.codemap/')) {
            await fs.appendFile(gitignorePath, '\n# Codebase Mapper\n.codemap/\n');
        }
    } catch (e) {
        await fs.writeFile(gitignorePath, '# Codebase Mapper\n.codemap/\n');
    }
}

function getHotspots(graph: CodeGraph) {
    const importCounts = new Map<string, number>();
    graph.links.filter(l => l.type === 'import').forEach(link => {
        importCounts.set(link.target, (importCounts.get(link.target) || 0) + 1);
    });

    return Array.from(importCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10)
        .map(([path, count]) => ({ path, count }));
}
